services:
  management-api:
    image: node:22-alpine
    working_dir: /app
    command: ["node", "management-api/server.js"]
    env_file:
      - .env
    environment:
      API_PORT: 3000
      WORKER_URL: http://worker:4100
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - worker

  scheduler:
    image: golang:1.25-alpine
    working_dir: /app
    command: ["go", "run", "./scheduler/cmd/scheduler"]
    env_file:
      - .env
    environment:
      API_PORT: 3000
      WORKER_URL: http://worker:4100
    volumes:
      - ./:/app
    depends_on:
      - management-api
      - worker

  worker:
    image: node:22-alpine
    working_dir: /app
    command: ["node", "workers/mock-worker/server.js"]
    env_file:
      - .env
    environment:
      WORKER_PORT: 4100
    volumes:
      - ./:/app
    ports:
      - "4100:4100"
